# Generated by Django 4.1.2 on 2023-01-02 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafe_app", "0002_koordinat_remove_cafe_koordinat"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=50)),
            ],
        ),
    ]
