# Generated by Django 4.1.2 on 2023-01-04 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cafe_app", "0003_user"),
    ]

    operations = [
        migrations.DeleteModel(name="User",),
    ]
